--Tính tổng tiền của 1 đơn hàng
CREATE FUNCTION F_TongTien_DonHang(@MaDH INT)
RETURNS MONEY
AS
BEGIN
DECLARE @Tong MONEY;
SELECT @Tong = SUM(SoLuong * GiaBan)
FROM CHITIETDONHANG WHERE MaDH = @MaDH;
RETURN @Tong;
END;
GO
--Kiểm tra tồn kho của 1 sản phẩm
CREATE FUNCTION F_KiemTraTonKho(@MaSP NVARCHAR(10))
RETURNS INT
AS
BEGIN
DECLARE @SL INT;
SELECT @SL = SoLuongTonKho FROM SANPHAM WHERE MaSP = @MaSP;
RETURN @SL;
END;
GO

--Lấy tên khách hàng theo mã KH
CREATE FUNCTION F_LayTenKH(@MaKH NVARCHAR(6))
RETURNS NVARCHAR(100)
AS
BEGIN
DECLARE @Ten NVARCHAR(100);
SELECT @Ten = HoTenKH FROM KHACHHANG WHERE MaKH = @MaKH;
RETURN @Ten;
END;
GO

--Lấy giá sản phẩm theo mã SP
CREATE FUNCTION F_LayGiaSP(@MaSP NVARCHAR(10))
RETURNS MONEY
AS
BEGIN
DECLARE @Gia MONEY;
SELECT @Gia = DonGia FROM SANPHAM WHERE MaSP = @MaSP;
RETURN @Gia;
END;
GO

--Tính tổng số lượng sản phẩm đã bán
CREATE FUNCTION F_TongSoLuongBan(@MaSP NVARCHAR(10))
RETURNS INT
AS
BEGIN
DECLARE @Tong INT;
SELECT @Tong = SUM(SoLuong) FROM CHITIETDONHANG WHERE MaSP = @MaSP;
RETURN @Tong;
END;
GO